### ISSUE TITLE
It won't open!

### ISSUE THREAD

**Issue by SkyryanMSM** [niemasd/Kimera#1]
When I was opening the Kimera Software! It says to me "Component 'Mscomct2.ocx' or one of its dependencies not correctly registered: a file is missing or invalid". How do I fix this issue?
![image](https://user-images.githubusercontent.com/94207134/141601263-e38593ae-d233-4e58-ae7e-5c44f002a053.png)

**Comment by niemasd** [comment]
Note that I'm not the developer of Kimera: I'm just mirroring it here just in case the links disappear. This might be useful: https://answers.microsoft.com/en-us/windows/forum/all/keep-getting-run-time-error-399-component/1474d050-1c80-4589-9c2c-038a48f9d74e
